In [1]:
import numpy as np

In [9]:
a = np.array([[1,2],[3,4]], dtype=np.float64)
b = np.array([[5,6],[7,8]], dtype=np.float64)

In [18]:
print(np.sqrt(a))
print(np.add(a,b))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 6.  8.]
 [10. 12.]]


In [23]:
x = np.array([[2,3],[4,5]])
y = np.array([[6,7],[8,9]])

v = np.array([6,7])
u = np.array([4,5])

print(np.dot(v,u))
print(x.dot(y))
print(np.dot(x,v))

59
[[36 41]
 [64 73]]
[33 59]


In [48]:
p = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
w = np.array([1,0,1])
q = np.empty_like(p)

for i in range(4):
    q[i, :] = p[i, :] + w
    
print(q)
ww = np.tile(w,(4,1))
print(ww)
print(np.add(p,ww))

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
