In [1]:
import numpy as np

In [9]:
a = np.array([[1,2],[3,4]], dtype=np.float64)
b = np.array([[5,6],[7,8]], dtype=np.float64)

In [10]:
c = a+b
c

array([[ 6.,  8.],
       [10., 12.]])

In [13]:
temp = np.add(a,b)
print(temp)

[[ 5. 12.]
 [21. 32.]]


In [14]:
print(np.sqrt(a))

[[1.         1.41421356]
 [1.73205081 2.        ]]
